name: "Semantic Pull Request Pre-Fill"
description: "Pre-fill a pull request description and title based on a semantic branch name"
inputs:
  branch:
    description: "The branch name to parse"
    required: true
outputs:
  title:
    description: "The title of the pull request"
  description:
    description: "The description of the pull request"
runs:
  using: "node16"
  main: "dist/index.js"
