name: 'Semantic Pull Request Pre-Fill'
description: 'Pre-fill a pull request description and title based on a semantic branch name'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  project-base-url:
    description: 'Base URL for the project/task/ticket system'
    required: false
  template-type:
    description: 'Template type. Currently "basic" and "conventional" are supported."'
    required: false
  title-format:
    description: 'Title format. Use the keywords "prefix", "ticket" and "description" as placeholders. You can check the default format and more examples in the README.'
    required: false
  custom-template:
    description: 'Custom template for the pull request description. Use the keywords "prefix", "ticket" and "description" as placeholders. You can check the default template and more examples in the README. If you use this input, the "template-type" input will be ignored.'
    required: false
  prefixes:
    description: 'List of prefixes to be used in the composing process.'
    required: false
    type: array
    items:
      type: string
  tickets:
    description: 'List of tickets to be used in the composing process.'
    required: false
    type: array
    items:
      type: string
  openai-token:
    description: 'OpenAI token. If set, the action will try to generate a pull request description using OpenAI.'
    required: false
  project-context:
    description: 'Project context. Used for the AI autocompletion.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
