name: 'Semantic Pull Request Pre-Fill'
description: 'Pre-fill a pull request description and title based on a semantic branch name'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  project-base-url:
    description: 'Base URL for the project/task/ticket system'
    required: false
  template-type:
    description: 'Template type. Currently "basic" and "conventional" are supported."'
    required: false
  title-format:
    description: 'Title format. Use the keywords "prefix", "ticket" and "description" as placeholders. You can check the default format and more examples in the README.'
    required: false
  custom-template:
    description: 'Custom template for the pull request description. Use the keywords "prefix", "ticket" and "description" as placeholders. You can check the default template and more examples in the README. If you use this input, the "template-type" input will be ignored.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
