name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  pull-requests: write

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Test action
        uses: ./
        with:
          branch: 'feat/xxx-000-test2'

      - name: Set the pull request title and description
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const inputs = context.payload.pull_request;

            console.log(process.env)

            const result = await github.pulls.update({
              ...context.repo,
              pull_number: inputs.number,
              title: '@TODO: output title',
              body: 'TODO: output body'
            });
